package general.files;

public enum DocumentModelChange {

    GRAPHFILELOADED,GRAPHFILEREMOVED,GRAPHFILEREMOVEDALL, GRAAFVISFILECREATED,GRAAFVISFILELOADED,GRAAFVISFILESAVED, SVGGENERATED, SVGREMOVED, SVGREMOVEDALL;
}
