package com.github.meteoorkip.general.files;

public enum FileModelChange {

    GRAPHFILELOADED,GRAPHFILEREMOVED,GRAPHFILEREMOVEDALL, GRAAFVISFILECREATED,GRAAFVISFILELOADED,GRAAFVISFILESAVED, SVGGENERATED, SVGREMOVED, SVGREMOVEDALL
}
